id: opecha:P000330
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG3399
  title: ཉི་ཁྲིའི་འགྲེལ་པ་
  volume:
    0c3291547b384ef89b4097e95cadf69e:
      image_group_id: I1KG3480
      title: Volume 1 of sher phyin stong phrag nyi shu lnga pa
      volume_number: 1
      total_pages: 1562
    3a8309627f044e2799ccba65dcd54c29:
      image_group_id: I1KG3481
      title: Volume 2 of sher phyin stong phrag nyi shu lnga pa
      volume_number: 2
      total_pages: 1588
    c251bf7dbe2b433cb6c57ce1980bd914:
      image_group_id: I1KG3482
      title: Volume 3 of sher phyin stong phrag nyi shu lnga pa
      volume_number: 3
      total_pages: 1726
  author: ''
ebook_metadata:
  title: ཉི་ཁྲིའི་འགྲེལ་པ་
  author: ''
  sku: P000330
  cover: cover.jpg
  layers:
  - pagination
