id: IA98A228D
legacy_id: P000330
ocr_import_info:
  bdrc_scan_id: W1KG3399
  source: bdrc
  ocr_info:
    timestamp: '2020-03-12T22:20:32'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T15:01:23.053192+00:00'
last_modified: 2022-08-31 23:03:10.883951
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG3399
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG3399
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཉི་ཁྲིའི་འགྲེལ་པ།
  author: སེངྒེ་བཟང་པོ།
statistics:
  ocr_word_mean_confidence_index: 0.8967610993176898
  ocr_word_median_confidence_index: 0.9700000286102295
quality: null
bases:
  I1KG3481:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG3481
      total_pages: 1588
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG3481.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.9065396918910793
    legacy_id: v002
  I1KG3480:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG3480
      total_pages: 1562
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG3480.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8819426431908143
    legacy_id: v001
  I1KG3482:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG3482
      total_pages: 1726
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1KG3482.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.9016393134946841
    legacy_id: v003
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
