id: IA98A228D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-12T22:31:21+00:00'
last_modified: '2022-06-15T16:31:08.754905+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG3399
  title: ཉི་ཁྲིའི་འགྲེལ་པ་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    91DA:
      image_group_id: I1KG3480
      title: Volume 1 of sher phyin stong phrag nyi shu lnga pa
      total_pages: 1562
      order: 1
      base_file: 91DA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
